# Inspecting normalizations

Note: This notebook should only be used to generate predictions on git branches created from a dvc experiment. On the main/dev branch this notebook will only be updated when changes to the code are necessary, but it will not be used to generate predictions there.

## Prepare data and get normalizations

In [2]:
import os
import random
import tomli

import datasets
import numpy as np
import pandas as pd
import torch
import transformers
from transnormer.models.train_model import tokenize_datasets
from transnormer.evaluation.analysis import get_spans_of_unknown_tokens
from transnormer.visualization.formatting import markup_spans

In [3]:
# Number of examples to generate predictions for
N = 100

In [3]:
# Load configs
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(''))) # "../../"
CONFIGFILE = os.path.join(ROOT, "training_config.toml")
with open(CONFIGFILE, mode="rb") as fp:
    CONFIGS = tomli.load(fp)

# OR: Use custom configs (if so: uncomment the following)
# CONFIGS = {
#     "gpu": "cuda:0",
#     "random_seed": 42,
#     "tokenizer": {
#         "max_length_input": 128,
#         "max_length_output": 128,
#         "input_transliterator": "Transliterator1",
#     },
#     "language_models": {
#         "checkpoint_encoder": "prajjwal1/bert-tiny",
#         "checkpoint_decoder": "prajjwal1/bert-tiny",
#     },
#     "beam_search_decoding": {
#         "no_repeat_ngram_size": 3,
#         "early_stopping": True,
#         "length_penalty": 2.0,
#         "num_beams": 4,
#     },
# }

In [4]:
# Fix seeds for reproducibilty
random.seed(CONFIGS["random_seed"])
np.random.seed(CONFIGS["random_seed"])
torch.manual_seed(CONFIGS["random_seed"])

# GPU set-up
device = torch.device(CONFIGS["gpu"] if torch.cuda.is_available() else "cpu")

In [5]:
# Load data 
data_files = {
    "1600to1699": os.path.join(ROOT, "data/interim/dtak-v03-1600-1699/dtak-v03-1600-1699-test.jsonl"),
    "1700to1799": os.path.join(ROOT, "data/interim/dtak-v03-1700-1799/dtak-v03-1700-1799-test.jsonl"),
    "1800to1899": os.path.join(ROOT, "data/interim/dtak-v03-1800-1899/dtak-v03-1800-1899-test.jsonl"),
}
ds = datasets.load_dataset("json", data_files=data_files)

ds["1600to1699"] = ds["1600to1699"].shuffle().select(range(N))
ds["1700to1799"] = ds["1700to1799"].shuffle().select(range(N))
ds["1800to1899"] = ds["1800to1899"].shuffle().select(range(N))

Using custom data configuration default-a90bb03161111f25
Found cached dataset json (/home/bracke/.cache/huggingface/datasets/json/default-a90bb03161111f25/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|██████████| 3/3 [00:00<00:00, 244.40it/s]
Loading cached shuffled indices for dataset at /home/bracke/.cache/huggingface/datasets/json/default-a90bb03161111f25/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-3624239f95833622.arrow
Loading cached shuffled indices for dataset at /home/bracke/.cache/huggingface/datasets/json/default-a90bb03161111f25/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-95c166b53ec58244.arrow
Loading cached shuffled indices for dataset at /home/bracke/.cache/huggingface/datasets/json/default-a90bb03161111f25/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-14fdad2bc2682aff.arrow

In [6]:
# Tokenize data 

# In case we use locally saved models for the tokenizers
# the relative path must be completed. Uncomment the respective line.
# CONFIGS["language_models"]["checkpoint_encoder"] = os.path.join(ROOT, CONFIGS["language_models"]["checkpoint_encoder"])
# CONFIGS["language_models"]["checkpoint_decoder"] = os.path.join(ROOT, CONFIGS["language_models"]["checkpoint_decoder"])

prepared_dataset, tokenizer_input, tokenizer_output = tokenize_datasets(ds, CONFIGS)

Parameter 'fn_kwargs'={'tokenizer_input': BertTokenizerFast(name_or_path='dbmdz/bert-base-historic-multilingual-cased', vocab_size=32000, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}), 'tokenizer_output': BertTokenizerFast(name_or_path='bert-base-multilingual-cased', vocab_size=119547, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}), 'max_length_input': 128, 'max_length_output': 128} of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
100%|██████████| 25/25 [00:00<00:00, 398.23ba/s]
100%|██████████| 25/25 [00:00<00:00, 346.21ba/s]
100%|██████████| 25/25 [00:00<00:00, 388.38ba/s]

In [7]:
# Load model
checkpoint = os.path.join(ROOT, "models/model/checkpoint-50000") # TODO
model = transformers.EncoderDecoderModel.from_pretrained(checkpoint).to(device)

In [8]:
# Generate normalizations
# TODO: Do we have to include a configuration for beam search decoding here?
def generate_normalization(batch):
    inputs = tokenizer_input(batch["orig"], padding="max_length", truncation=True, max_length=128, return_tensors="pt")
    input_ids = inputs.input_ids.to(device)
    attention_mask = inputs.attention_mask.to(device)

    outputs = model.generate(input_ids, attention_mask=attention_mask)
    del input_ids, attention_mask # free memory
    output_str = tokenizer_output.batch_decode(outputs, skip_special_tokens=True)

    batch["norm_pred_str"] = output_str

    return batch


ds = ds.map(
    generate_normalization, 
    batched=True, 
    batch_size=2, 
    load_from_cache_file=False,
    )

  0%|          | 0/50 [00:00<?, ?ba/s]/home/bracke/miniconda3/envs/gpu-venv-transnormer/lib/python3.9/site-packages/transformers/generation/utils.py:1186: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/home/bracke/miniconda3/envs/gpu-venv-transnormer/lib/python3.9/site-packages/transformers/generation/utils.py:1273: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 128 (`generation_config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
100%|██████████| 50/50 [01:36<00:00,  1.93s/ba]
100%|██████████| 50/50 [01:33<00:00,  1.86s/ba]
100%|██████████| 50/50 [02:15<00:00,  2.72s/ba]

### Apply visual modifications


1. Markup unknown tokens in red
2. Add token-separator ("|") in input text
2. Add token-separator ("|") in output text

In [11]:
# Apply HTML markup to unknown tokens in original text
def markup_unknown_tokens(batch):
    spans = get_spans_of_unknown_tokens(batch["orig"], tokenizer_input)
    text_marked_up = markup_spans(batch["orig"], spans, opening_tag="<span style='color:#FF0000'>")

    batch["orig_marked_up"] = text_marked_up
    return batch

ds = ds.map(markup_unknown_tokens, batched=False, load_from_cache_file=False)

100%|██████████| 100/100 [00:00<00:00, 4178.93ex/s]
100%|██████████| 100/100 [00:00<00:00, 4358.99ex/s]
100%|██████████| 100/100 [00:00<00:00, 3594.80ex/s]

In [12]:
# Add token-separator 
def separate_tokens(batch, column, tokenizer):
    # We have to do the normalization explicitly before getting the encoding
    # to avoid mismatches in case the normalization changes the string length, e.g. "æ -> ae"
    norm_str = tokenizer.backend_tokenizer.normalizer.normalize_str(batch[column])
    encoding = tokenizer(norm_str, add_special_tokens=False)
    spans = [
        # map a token index to a pair of character indices
        encoding.token_to_chars(token_index)[:] for token_index in range(len(encoding["input_ids"]))
    ]
    text_marked_up = markup_spans(
        tokenizer.backend_tokenizer.normalizer.normalize_str(batch[column]),
        spans,
        opening_tag="",
        closing_tag="<span style='color:#FFA500'>|</span>",
        )

    batch[f"{column}_xlit_tok"] = text_marked_up
    return batch

ds = ds.map(separate_tokens, fn_kwargs={"tokenizer":tokenizer_input, "column" : "orig"}, batched=False, load_from_cache_file=False)
ds = ds.map(separate_tokens, fn_kwargs={"tokenizer":tokenizer_output, "column" : "norm_pred_str"}, batched=False, load_from_cache_file=False)

100%|██████████| 100/100 [00:00<00:00, 2513.79ex/s]
100%|██████████| 100/100 [00:00<00:00, 3569.89ex/s]
100%|██████████| 100/100 [00:00<00:00, 2932.20ex/s]
100%|██████████| 100/100 [00:00<00:00, 4293.26ex/s]
100%|██████████| 100/100 [00:00<00:00, 4135.01ex/s]
100%|██████████| 100/100 [00:00<00:00, 3557.48ex/s]

In [13]:
# Create pandas dataframes from predictions

# Do no truncate cells with long text
pd.set_option('display.max_colwidth', None)

part = "1600to1699"
df1600to1699 = pd.DataFrame(
    data={
        "orig" : ds[part]["orig"],
        "pred" : ds[part]["norm_pred_str"],
        "cab" : ds[part]["norm"],
        # "orig_xlit" : ds[part]["orig_xlit_tok"], 
        # "norm_tok" : ds[part]["norm_pred_str_xlit_tok"], 
        }
    )

part = "1700to1799"
df1700to1799 = pd.DataFrame(
    data={
        "orig" : ds[part]["orig"],
        "pred" : ds[part]["norm_pred_str"],
        "cab" : ds[part]["norm"],
        # "orig_xlit" : ds[part]["orig_xlit_tok"], 
        # "norm_tok" : ds[part]["norm_pred_str_xlit_tok"], 
        }
    )

part = "1800to1899"
df1800to1899 = pd.DataFrame(
    data={
        "orig" : ds[part]["orig"],
        "pred" : ds[part]["norm_pred_str"],
        "cab" : ds[part]["norm"],
        # "orig_xlit" : ds[part]["orig_xlit_tok"], 
        # "norm_tok" : ds[part]["norm_pred_str_xlit_tok"], 
        }
    )

---

In [14]:
from diff_match_patch import diff_match_patch
dmp = diff_match_patch()

df1600to1699["pred_diff"] = [
    dmp.diff_prettyHtml(dmp.diff_main(cab,pred)) 
    for (cab,pred) in zip(df1600to1699["cab"], df1600to1699["pred"]) 
    ]

df1600to1699["cab_diff"] = [
    dmp.diff_prettyHtml(dmp.diff_main(pred,cab)) 
    for (pred,cab) in zip(df1600to1699["pred"], df1600to1699["cab"]) 
    ]

df1600to1699 = df1600to1699.applymap(lambda x : x.replace('style="background:#ffe6e6;"','style="background:#c94d4d;"'))
df1600to1699 = df1600to1699.applymap(lambda x : x.replace('style="background:#e6ffe6;"','style="background:#5cd15c;"'))

Single example:

In [16]:
s= "Groß-Fuͤrſten in Finland/ Hertzogen zu Schonen/ Eheſten/ Lieffland/ Carelen/ Bremen/ Vehrden/ Stettin/ Pommern/ der Caſſuben und Wenden/"
inputs = tokenizer_input(s, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
input_ids = inputs.input_ids.to(device)
attention_mask = inputs.attention_mask.to(device)

outputs = model.generate(input_ids, attention_mask=attention_mask)
del input_ids, attention_mask # free memory
output_str = tokenizer_output.batch_decode(outputs, skip_special_tokens=True)

from IPython.core.display import HTML
df_example = pd.DataFrame(data=output_str)
display(HTML(df_example.head(1).to_html(escape=False)))

/home/bracke/miniconda3/envs/gpu-venv-transnormer/lib/python3.9/site-packages/transformers/generation/utils.py:1273: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 128 (`generation_config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

---

## Look at the dataframes

### 1600 to 1699

In [17]:
from IPython.core.display import HTML
display(HTML(df1600to1699[["orig", "pred_diff", "cab_diff"]].head(N).to_html(escape=False)))

Same with other model

In [ ]:
# Load model
checkpoint2 = "/home/bracke/models/models_2023-03-16_15-24/checkpoint-100000/"
CONFIGFILE2 = "/home/bracke/models/models_2023-03-16_15-24/training_config.toml"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(''))) # "../../"
with open(CONFIGFILE2, mode="rb") as fp:
    CONFIGS2 = tomli.load(fp)
# Fix seeds for reproducibilty
random.seed(CONFIGS2["random_seed"])
np.random.seed(CONFIGS2["random_seed"])
torch.manual_seed(CONFIGS2["random_seed"])

# GPU set-up
device = torch.device(CONFIGS2["gpu"] if torch.cuda.is_available() else "cpu")
# Load data 
data_files = {
    "1600to1699": os.path.join(ROOT, "data/interim/dtak-v03-1600-1699/dtak-v03-1600-1699-test.jsonl"),
    "1700to1799": os.path.join(ROOT, "data/interim/dtak-v03-1700-1799/dtak-v03-1700-1799-test.jsonl"),
    "1800to1899": os.path.join(ROOT, "data/interim/dtak-v03-1800-1899/dtak-v03-1800-1899-test.jsonl"),
}
ds2 = datasets.load_dataset("json", data_files=data_files)

ds2["1600to1699"] = ds2["1600to1699"].shuffle().select(range(N))
ds2["1700to1799"] = ds2["1700to1799"].shuffle().select(range(N))
ds2["1800to1899"] = ds2["1800to1899"].shuffle().select(range(N))

model2 = transformers.EncoderDecoderModel.from_pretrained(checkpoint2).to(device)
prepared_dataset, tokenizer_input, tokenizer_output = tokenize_datasets(ds2, CONFIGS2)

In [ ]:
def generate_normalization(batch):
    inputs = tokenizer_input(batch["orig"], padding="max_length", truncation=True, max_length=128, return_tensors="pt")
    input_ids = inputs.input_ids.to(device)
    attention_mask = inputs.attention_mask.to(device)

    outputs = model2.generate(input_ids, attention_mask=attention_mask)
    del input_ids, attention_mask # free memory
    output_str = tokenizer_output.batch_decode(outputs, skip_special_tokens=True)

    batch["norm_pred_str"] = output_str

    return batch

ds2 = ds2.map(generate_normalization, batched=True, batch_size=2, load_from_cache_file=False, )

In [7]:
# Create pandas dataframes from predictions

# Do no truncate cells with long text
pd.set_option('display.max_colwidth', None)

part = "1600to1699"
df1600to1699 = pd.DataFrame(
    data={
        "orig" : ds2[part]["orig"],
        "pred" : ds2[part]["norm_pred_str"],
        "cab" : ds2[part]["norm"],
        }
    )

part = "1700to1799"
df1700to1799 = pd.DataFrame(
    data={
        "orig" : ds2[part]["orig"],
        "pred" : ds2[part]["norm_pred_str"],
        "cab" : ds2[part]["norm"],
        }
    )

part = "1800to1899"
df1800to1899 = pd.DataFrame(
    data={
        "orig" : ds2[part]["orig"],
        "pred" : ds2[part]["norm_pred_str"],
        "cab" : ds2[part]["norm"],
        }
    )

from diff_match_patch import diff_match_patch
dmp = diff_match_patch()

df1600to1699["pred_diff"] = [
    dmp.diff_prettyHtml(dmp.diff_main(cab,pred)) 
    for (cab,pred) in zip(df1600to1699["cab"], df1600to1699["pred"]) 
    ]

df1600to1699["cab_diff"] = [
    dmp.diff_prettyHtml(dmp.diff_main(pred,cab)) 
    for (pred,cab) in zip(df1600to1699["pred"], df1600to1699["cab"]) 
    ]

df1600to1699 = df1600to1699.applymap(lambda x : x.replace('style="background:#ffe6e6;"','style="background:#c94d4d;"'))
df1600to1699 = df1600to1699.applymap(lambda x : x.replace('style="background:#e6ffe6;"','style="background:#5cd15c;"'))

from IPython.core.display import HTML
display(HTML(df1600to1699[["orig", "pred_diff", "cab_diff"]].head(N).to_html(escape=False)))

### 1700 to 1799

In [ ]:
from IPython.core.display import HTML
display(HTML(df1700to1799.head(N).to_html(escape=False)))

### 1800 to 1899

In [ ]:
from IPython.core.display import HTML
display(HTML(df1800to1899.head(N).to_html(escape=False)))

---